version: '3.8'

services:
  mongodb:
    container_name: mongo
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - dialernet

  server:
    container_name: server
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - dialernet
    command: node ./server/dist/index.js

  app:
    container_name: web
    depends_on:
      - server
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - dialernet
    command: yarn --cwd ./react-ui start

  localstack: #S3 only
    profiles: ["full"]
    image: localstack/localstack:latest
    container_name: localstack-s3
    environment:
     - SERVICES=s3:5002
     - DEFAULT_REGION=us-east-2
     - DATA_DIR=/tmp/localstack/data
    ports:
     - 5002:5002
     - 9999:8080
     - 4566:4566
    volumes:
      - localstack-data:/tmp/localstack
    
volumes:
  db:
  localstack-data:
    name: localstack-data

networks:
  dialernet:
    driver: bridge